import { Product } from './types/Product'

export const sampleProducts: Product[] = [
  {
    name: 'Flower Gift',
    slug: 'flower-gift',
    image: '../images/f1.jpg',
    category: 'Flowers',
    brand: 'Flowers',
    price: 35,
    countInStock: 20,
    description: 'Gift Flowers',
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: 'Box Flower',
    slug: 'box-flower2',
    image: '../images/f2.jpg',
    category: 'Flowers',
    brand: 'Flowers',
    price: 45,
    countInStock: 20,
    description: 'Box Flowers',
    rating: 3.5,
    numReviews: 8,
  },
  {
    name: 'Box Flower',
    slug: 'box-flower',
    image: '../images/f3.jpg',
    category: 'Flowers',
    brand: 'Flowers',
    price: 45,
    countInStock: 20,
    description: 'Box Flowers',
    rating: 3.5,
    numReviews: 8,
  },
  {
    name: 'Basket Flower',
    slug: 'basket-flower',
    image: '../images/f4.jpg',
    category: 'Flowers',
    brand: 'Flowers',
    price: 25,
    countInStock: 20,
    description: 'Basket Flower',
    rating: 3.5,
    numReviews: 8,
  },
]
